#!/bin/bash

compiler_opts="-I src/inc -include src/inc/lib.h -nostdlib -ffreestanding"

location() { echo "$1"; mkdir -p "${1%/*}"; }

compile() {
	loc="${2%.*}"
	loc="$1/${loc##*/}.o"
	clang $compiler_opts -c $2 -o "$(location $loc)"
	echo $loc
}

build() {
	echo "bin/main"
	for f in src/*.c
		{ obj_list+=" $(compile "bin/obj" $f)"; }
	clang $compiler_opts $obj_list -o "$(location bin/main)"
}

case "$1" in
all|"") echo $(build) ;;
run) 	$($0) ;;
clean)  rm -r bin src/*.c.o ;;
esac
