#!/bin/bash

case "$1" in
all|"")
	mkdir -p bin
	clang  -nostdlib -ffreestanding -o bin/main src/start.c
	;;
clean) 
	rm -r bin
	;;
asm) 
	clang -nostdlib -ffreestanding -S -o 'bin/start.s' 'src/ini.c'
	nvim bin/start.s
	;;
run)
	mkdir -p bin
	clang -nostdlib -ffreestanding -O3 -o bin/main src/ini.c
	./bin/main arg1 arg2 arg3
	;;
pp)
	mkdir -p bin
	clang -nostdlib -ffreestanding -E -o start.c src/start.c
	nvim start.c
	;;
esac
